services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./unified_agent_system/qdrant_storage:/qdrant/storage

  fastapi:
    build: ./unified_agent_system
    container_name: fastapi
    ports:
      - "80:80"
    env_file:
      - ./unified_agent_system/.env
    volumes:
      - ./data:/app/data 
    depends_on:
      - qdrant
